server:
  port: ${SERVER_PORT:9092}

spring:
  application:
    name: user-service

  security:
    user:
      name: ${APP_SECURITY_USERNAME:green}
      password: ${APP_SECURITY_PASSWORD:change-me}

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/user_management?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:change-me}

  jpa:
    hibernate:
      ddl-auto: none

    open-in-view: false

    properties:
      javax:
        persistence:
          validation:
            mode: none

password:
  hashing:
    algo:
      argon2:
        type: 1
        saltLength: 16
        hashLength: 32
        iterations: 4
        memory: 65586
        parrallelism: 2

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always

info:
  app:
    name: User Microservice
    version: 1.0.0
    description: User management service