server:
  port: ${SERVER_PORT:9091}

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/shopping}

  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8081}
        instance:
          service-base-url: ${SERVICE_BASE_URL:http://localhost:9091}

logging:
  level:
    root: INFO
    com.greenlearner.product: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always

  health:
    mongo:
      enabled: true

info:
  app:
    name: Product Microservice
    version: 1.0.0
    description: Add and retrieve product information

product:
  currencies:
    - INR
    - USD
    - EUR